name: Windup PR/Push UI

on:
  pull_request:
    branches:
      - master
      - 'releases/**'
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        working-directory: pf-ui/src/main/webapp
        run: |
          npm install
          npm run build
